### PR TITLE
updated mousepad and thunar

### PR DESCRIPTION
**Pull request by treeman1111**
As part of FL-2162, I have updated the ebuild for mousepad from 0.3.0 to 0.4.0. I also "updated" (copied the 1.6.3 ebuild) the thunar ebuild to 1.6.6. Both of the ebuilds seem to function in tests on my system. Is it OK for me to create a fork of this repo and to submit changes this way?

Best,
Duncan

### CODE REVIEW

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2165

**Comment by danielrobbins** [comment]
Yes, you can fork the repo on GitHub and send a pull request if you like.

**Comment by treeman1111** [comment]
Thanks for the info. If the changes are coming upstream, is this necessary?

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.

**Pull request closed without merging**
